// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDoListFuckThis.Data;

#nullable disable

namespace ToDoListFuckThis.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107123222_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDoListFuckThis.Models.ProjectRoles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("projectsId")
                        .HasColumnType("uuid");

                    b.Property<int>("roleProject")
                        .HasColumnType("integer");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("projectsId");

                    b.HasIndex("userId");

                    b.ToTable("projectRoles");
                });

            modelBuilder.Entity("ToDoListFuckThis.Models.Projects", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("ToDoListFuckThis.Models.TodoSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProjectsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectsId");

                    b.ToTable("todoSections");
                });

            modelBuilder.Entity("ToDoListFuckThis.Models.Todolists", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("TaskStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TodoSectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TodoSectionId");

                    b.ToTable("todolists");
                });

            modelBuilder.Entity("ToDoListFuckThis.Models.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("ImagesUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectsId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectsId");

                    b.ToTable("user");
                });

            modelBuilder.Entity("ToDoListFuckThis.Models.ProjectRoles", b =>
                {
                    b.HasOne("ToDoListFuckThis.Models.Projects", "projects")
                        .WithMany()
                        .HasForeignKey("projectsId");

                    b.HasOne("ToDoListFuckThis.Models.Users", "user")
                        .WithMany()
                        .HasForeignKey("userId");

                    b.Navigation("projects");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ToDoListFuckThis.Models.TodoSection", b =>
                {
                    b.HasOne("ToDoListFuckThis.Models.Projects", null)
                        .WithMany("Todosection")
                        .HasForeignKey("ProjectsId");
                });

            modelBuilder.Entity("ToDoListFuckThis.Models.Todolists", b =>
                {
                    b.HasOne("ToDoListFuckThis.Models.TodoSection", null)
                        .WithMany("Todolists")
                        .HasForeignKey("TodoSectionId");
                });

            modelBuilder.Entity("ToDoListFuckThis.Models.Users", b =>
                {
                    b.HasOne("ToDoListFuckThis.Models.Projects", null)
                        .WithMany("Users")
                        .HasForeignKey("ProjectsId");
                });

            modelBuilder.Entity("ToDoListFuckThis.Models.Projects", b =>
                {
                    b.Navigation("Todosection");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ToDoListFuckThis.Models.TodoSection", b =>
                {
                    b.Navigation("Todolists");
                });
#pragma warning restore 612, 618
        }
    }
}
